import { angle, choice, color, number, percent, toggle } from "../../parameter-builders";
import type { EffectDefinition } from "../../types";

export const COLOR_EFFECTS: EffectDefinition[] = [
  {
    type: "photo-filter",
    name: "Photo Filter",
    category: "Color Correction",
    description: "Apply a photographic warming, cooling, or custom-color filter in linear light.",
    execution: "fused-pixel",
    parameters: [
      color("color", "Filter Color", 0xffa34d),
      percent("density", "Density", 25),
      toggle("preserveLuminance", "Preserve Luminosity", 1),
      number("exposure", "Filter Exposure", 0, -4, 4, 0.05, "EV"),
    ],
  },
  {
    type: "selective-color",
    name: "Selective Color",
    category: "Color Correction",
    description: "Adjust CMYK contributions inside a perceptually selected color family.",
    execution: "fused-pixel",
    parameters: [
      choice("target", "Colors", [
        "Reds",
        "Yellows",
        "Greens",
        "Cyans",
        "Blues",
        "Magentas",
        "Whites",
        "Neutrals",
        "Blacks",
      ]),
      number("cyan", "Cyan", 0, -100, 100, 1, "%"),
      number("magenta", "Magenta", 0, -100, 100, 1, "%"),
      number("yellow", "Yellow", 0, -100, 100, 1, "%"),
      number("black", "Black", 0, -100, 100, 1, "%"),
      toggle("relative", "Relative", 1),
    ],
  },
  {
    type: "shadows-highlights",
    name: "Shadow / Highlight",
    category: "Color Correction",
    description: "Recover shadow and highlight detail using luminance-weighted tonal compression.",
    execution: "fused-pixel",
    parameters: [
      percent("shadows", "Shadow Amount", 30),
      percent("highlights", "Highlight Amount", 20),
      percent("shadowWidth", "Shadow Tonal Width", 50),
      percent("highlightWidth", "Highlight Tonal Width", 50),
      percent("colorCorrection", "Color Correction", 20),
      number("midtoneContrast", "Midtone Contrast", 0, -1, 1, 0.01),
    ],
  },
  {
    type: "gamma-pedestal-gain",
    name: "Gamma / Pedestal / Gain",
    category: "Color Correction",
    description: "Grade channel gain, black pedestal, and gamma in a single GPU operation.",
    execution: "fused-pixel",
    parameters: [
      number("gamma", "Gamma", 1, 0.05, 8, 0.01),
      number("pedestal", "Pedestal", 0, -1, 1, 0.005),
      number("gain", "Gain", 1, 0, 16, 0.01),
      number("redGain", "Red Gain", 1, 0, 8, 0.01),
      number("greenGain", "Green Gain", 1, 0, 8, 0.01),
      number("blueGain", "Blue Gain", 1, 0, 8, 0.01),
    ],
  },
  {
    type: "hdr-compander",
    name: "HDR Compander",
    category: "Color Correction",
    description: "Compress or expand high-dynamic-range values above a configurable threshold.",
    execution: "fused-pixel",
    parameters: [
      choice("mode", "Mode", ["Compress", "Expand"]),
      number("threshold", "Threshold", 0.7, 0.001, 16, 0.01),
      number("ratio", "Ratio", 4, 1, 32, 0.1),
      number("exposure", "Exposure", 0, -8, 8, 0.05, "EV"),
      percent("blend", "Blend With Original", 100),
    ],
  },
  {
    type: "broadcast-colors",
    name: "Broadcast Colors",
    category: "Color Correction",
    description: "Constrain luma and chroma excursions for broadcast-safe output monitoring.",
    execution: "fused-pixel",
    parameters: [
      choice("standard", "Broadcast Locale", ["NTSC", "PAL"]),
      number("maximumSignal", "Maximum Signal", 1, 0.1, 4, 0.01),
      choice("method", "How to Make Color Safe", ["Reduce Luminance", "Reduce Saturation"]),
      number("softness", "Softness", 0.08, 0, 1, 0.005),
      percent("blend", "Blend With Original", 100),
    ],
  },
  {
    type: "white-balance",
    name: "White Balance",
    category: "Color Correction",
    description: "Adapt color temperature and green-magenta tint while preserving scene luminance.",
    execution: "fused-pixel",
    parameters: [
      number("temperature", "Temperature", 0, -1, 1, 0.01),
      number("tint", "Tint", 0, -1, 1, 0.01),
      percent("adaptation", "Chromatic Adaptation", 100),
      toggle("preserveLuminance", "Preserve Luminosity", 1),
    ],
  },
  {
    type: "color-emboss",
    name: "Color Emboss",
    category: "Stylize",
    description: "Emboss source detail while retaining its original chromatic information.",
    execution: "fused-pixel",
    parameters: [
      angle("direction", "Direction", 135),
      number("relief", "Relief", 2, 0.25, 128, 0.25, "px"),
      number("contrast", "Contrast", 1.5, 0, 8, 0.05),
      percent("blend", "Blend With Original", 100),
    ],
  },
];
