import { angle, color, number, percent } from "../../parameter-builders";
import type { EffectDefinition } from "../../types";

export const LIGHTING_EFFECTS: EffectDefinition[] = [
  {
    type: "light-rays",
    name: "CC Light Rays",
    category: "Generate",
    description: "Sample thresholded HDR rays toward a movable light source.",
    execution: "multi-pass",
    parameters: [
      percent("centerX", "Center X", 50),
      percent("centerY", "Center Y", 50),
      number("length", "Ray Length", 240, 0, 4000, 1, "px"),
      number("threshold", "Threshold", 0.55, 0, 4, 0.01),
      number("intensity", "Intensity", 1.5, 0, 20, 0.05),
      color("color", "Ray Color", 0xb8e7ff),
      percent("blend", "Blend With Original", 100),
    ],
  },
  {
    type: "spotlight",
    name: "CC Spotlight",
    category: "Generate",
    description: "Project a feathered directional cone with distance falloff.",
    execution: "fused-pixel",
    parameters: [
      percent("sourceX", "Light X", 50),
      percent("sourceY", "Light Y", 15),
      percent("targetX", "Target X", 50),
      percent("targetY", "Target Y", 65),
      angle("coneAngle", "Cone Angle", 38),
      angle("feather", "Cone Feather", 12),
      number("falloff", "Distance Falloff", 1.5, 0, 8, 0.05),
      number("intensity", "Intensity", 1.4, 0, 20, 0.05),
      color("color", "Light Color", 0xffe8bc),
    ],
  },
  {
    type: "light-leak",
    name: "Light Leak",
    category: "Generate",
    description: "Animate broad film-style edge leaks from deterministic colored turbulence.",
    execution: "fused-pixel",
    parameters: [
      angle("angle", "Leak Angle", 18),
      number("width", "Leak Width", 0.32, 0.01, 2, 0.01),
      number("softness", "Softness", 0.45, 0.01, 2, 0.01),
      number("intensity", "Intensity", 1.2, 0, 12, 0.05),
      color("colorA", "Inner Color", 0xff4e36),
      color("colorB", "Outer Color", 0xffc65a),
      number("speed", "Animation Speed", 0.35, -10, 10, 0.05),
      number("seed", "Random Seed", 1, 0, 65535, 1),
      percent("blend", "Blend With Original", 75),
    ],
  },
  {
    type: "anamorphic-flare",
    name: "Anamorphic Flare",
    category: "Generate",
    description: "Generate an HDR anamorphic streak with halo and lens ghosts.",
    execution: "fused-pixel",
    parameters: [
      percent("centerX", "Center X", 50),
      percent("centerY", "Center Y", 50),
      angle("angle", "Streak Angle", 0),
      number("length", "Streak Length", 640, 1, 8000, 1, "px"),
      number("width", "Streak Width", 6, 0.5, 500, 0.5, "px"),
      number("intensity", "Intensity", 2, 0, 20, 0.05),
      number("ghosts", "Ghost Intensity", 0.55, 0, 4, 0.01),
      color("color", "Flare Color", 0x78bfff),
    ],
  },
  {
    type: "volumetric-fog",
    name: "Volumetric Fog",
    category: "Generate",
    description: "Composite animated multi-octave fog with height falloff.",
    execution: "compute",
    parameters: [
      percent("density", "Density", 45),
      number("scale", "Fog Scale", 280, 4, 4000, 1, "px"),
      number("height", "Height Falloff", 1.3, 0, 8, 0.05),
      number("speedX", "Drift X", 18, -1000, 1000, 1, "px/s"),
      number("speedY", "Drift Y", -4, -1000, 1000, 1, "px/s"),
      color("color", "Fog Color", 0x7894c7),
      percent("blend", "Blend With Original", 75),
    ],
  },
  {
    type: "caustics",
    name: "Caustics",
    category: "Generate",
    description: "Generate animated refractive interference highlights for water-like surfaces.",
    execution: "compute",
    parameters: [
      number("scale", "Scale", 90, 2, 2000, 1, "px"),
      number("speed", "Speed", 1.2, -20, 20, 0.05),
      number("complexity", "Complexity", 3, 1, 8, 1),
      number("intensity", "Intensity", 1.4, 0, 12, 0.05),
      number("depth", "Water Depth", 0.8, 0, 4, 0.01),
      color("color", "Caustic Color", 0x79d8ff),
      percent("blend", "Blend With Original", 70),
    ],
  },
  {
    type: "god-rays",
    name: "God Rays",
    category: "Generate",
    description: "Accumulate thresholded radial light with density, decay, and exposure controls.",
    execution: "multi-pass",
    parameters: [
      percent("centerX", "Light X", 50),
      percent("centerY", "Light Y", 20),
      number("density", "Density", 0.75, 0, 2, 0.01),
      number("decay", "Decay", 0.92, 0, 1, 0.005),
      number("weight", "Weight", 0.28, 0, 4, 0.01),
      number("threshold", "Threshold", 0.6, 0, 4, 0.01),
      number("exposure", "Exposure", 1.2, 0, 12, 0.05),
      color("color", "Ray Color", 0xffe7bb),
    ],
  },
  {
    type: "laser",
    name: "Laser",
    category: "Generate",
    description: "Draw a pulsing HDR laser between two points with core and halo controls.",
    execution: "fused-pixel",
    parameters: [
      percent("startX", "Start X", 20),
      percent("startY", "Start Y", 50),
      percent("endX", "End X", 80),
      percent("endY", "End Y", 50),
      number("core", "Core Width", 2, 0.25, 128, 0.25, "px"),
      number("glow", "Glow Width", 18, 0.5, 500, 0.5, "px"),
      number("intensity", "Intensity", 2.5, 0, 20, 0.05),
      number("pulse", "Pulse Amount", 0.35, 0, 1, 0.01),
      number("speed", "Pulse Speed", 3, 0, 30, 0.1),
      color("color", "Laser Color", 0x50d4ff),
    ],
  },
];
