// Joint angles and proportions for the shared forward-kinematic character rig.
const rest = {
  hipL: 0,
  kneeL: 0,
  hipR: 0,
  kneeR: 0,
  shoulderL: 8,
  elbowL: -3,
  shoulderR: -8,
  elbowR: 3,
  body: 0,
  head: 0,
};
export const poses = {
  stand: rest,
  sit: {
    ...rest,
    upperLeg: 110,
    lowerLeg: 185,
    hipL: -42,
    kneeL: 39,
    hipR: -49,
    kneeR: 46,
    shoulderL: -3,
    elbowL: -45,
    shoulderR: -14,
    elbowR: 27,
    body: 14,
    head: 12,
  },
  seesaw: {
    ...rest,
    upperLeg: 76,
    lowerLeg: 73,
    armUpper: 80,
    armLower: 75,
    shoulderY: -137,
    neckY: -154,
    headScale: 82,
    bodyY: -63,
    bodyScaleY: 90,
    hipL: 2,
    kneeL: -3,
    hipR: -2,
    kneeR: 3,
    shoulderL: 14,
    elbowL: 4,
    shoulderR: -10,
    elbowR: -5,
    head: 5,
  },
  slide: {
    ...rest,
    upperLeg: 105,
    lowerLeg: 100,
    armUpper: 80,
    armLower: 75,
    neckY: -152,
    headScale: 105,
    hipL: 68,
    kneeL: -39,
    hipR: -60,
    kneeR: 105,
    shoulderL: 158,
    elbowL: -150,
    shoulderR: -18,
    elbowR: 12,
    body: 20,
    head: 6,
  },
  float: {
    ...rest,
    hipL: 24,
    kneeL: -35,
    hipR: -42,
    kneeR: 76,
    shoulderL: 45,
    elbowL: -72,
    shoulderR: -62,
    elbowR: 15,
    body: -12,
    head: 8,
  },
  spread: {
    ...rest,
    hipL: 28,
    kneeL: -38,
    hipR: -50,
    kneeR: 22,
    shoulderL: 75,
    elbowL: -4,
    shoulderR: -104,
    elbowR: 8,
    body: -28,
    head: 20,
  },
  umbrella: {
    ...rest,
    hipL: -45,
    kneeL: 62,
    hipR: 4,
    kneeR: 16,
    shoulderL: 4,
    elbowL: 3,
    shoulderR: 4,
    elbowR: -138,
    body: 4,
    head: -12,
  },
  parade: {
    ...rest,
    upperLeg: 130,
    lowerLeg: 130,
    armUpper: 40,
    armLower: 40,
    rightUpperArm: 80,
    rightLowerArm: 75,
    shoulderY: -122,
    neckY: -129,
    bodyY: -60,
    bodyScaleY: 80,
    shoulderL: 0,
    elbowL: 0,
    shoulderR: -8,
    elbowR: -8,
  },
  crouch: {
    ...rest,
    hipL: -65,
    kneeL: 125,
    hipR: -53,
    kneeR: 119,
    shoulderL: 22,
    elbowL: -100,
    shoulderR: -18,
    elbowR: -120,
    body: 22,
    head: -20,
  },
  kiss: {
    ...rest,
    upperLeg: 145,
    lowerLeg: 185,
    hipL: -14,
    kneeL: 8,
    hipR: -24,
    kneeR: 12,
    shoulderL: -15,
    elbowL: -60,
    shoulderR: -20,
    elbowR: -75,
    body: 14,
    head: 8,
  },
  cuddle: {
    ...rest,
    upperLeg: 120,
    lowerLeg: 124,
    rightUpperLeg: 110,
    rightLowerLeg: 95,
    armUpper: 75,
    armLower: 85,
    shoulderY: -145,
    neckX: 14,
    neckY: -188,
    headScale: 90,
    hipL: -8,
    kneeL: 28,
    hipR: -9,
    kneeR: -22,
    shoulderL: 45,
    elbowL: -5,
    shoulderR: -65,
    elbowR: 92,
    body: 0,
    head: 5,
  },
  dive: {
    ...rest,
    shoulderL: 172,
    elbowL: 4,
    shoulderR: -172,
    elbowR: -4,
    hipL: 2,
    hipR: -2,
  },
  carry: { ...rest, upperLeg: 145, lowerLeg: 185 },
  lap: {
    ...rest,
    upperLeg: 110,
    lowerLeg: 145,
    hipL: -15,
    kneeL: 43,
    hipR: -40,
    kneeR: 42,
    shoulderL: 5,
    elbowL: -55,
    shoulderR: -8,
    elbowR: 64,
    body: 0,
    head: -8,
  },
  greeting: { ...rest, shoulderL: 165, elbowL: -25, shoulderR: -24, elbowR: 0, body: 12, head: -8 },
};
