import { angle, choice, number, percent } from "../../parameter-builders";
import type { EffectDefinition } from "../../types";

const point = (key: string, label: string, defaultValue: number) =>
  number(key, label, defaultValue, -100, 200, 0.1, "%");

export const ADVANCED_DISTORT_EFFECTS: EffectDefinition[] = [
  {
    type: "bezier-warp",
    name: "Bezier Warp",
    category: "Distort",
    description: "Bend all four edges with a compact bicubic-style GPU deformation.",
    execution: "fused-pixel",
    parameters: [
      number("topBend", "Top Bend", 0, -2000, 2000, 1, "px"),
      number("bottomBend", "Bottom Bend", 0, -2000, 2000, 1, "px"),
      number("leftBend", "Left Bend", 0, -2000, 2000, 1, "px"),
      number("rightBend", "Right Bend", 0, -2000, 2000, 1, "px"),
      percent("blend", "Blend", 100),
    ],
  },
  {
    type: "flo-motion",
    name: "CC Flo Motion",
    category: "Distort",
    description: "Push or pull pixels around two independently animated flow knots.",
    execution: "fused-pixel",
    parameters: [
      point("knot1X", "Knot 1 X", 35),
      point("knot1Y", "Knot 1 Y", 50),
      number("amount1", "Knot 1 Amount", 80, -1000, 1000, 1, "px"),
      point("knot2X", "Knot 2 X", 65),
      point("knot2Y", "Knot 2 Y", 50),
      number("amount2", "Knot 2 Amount", -80, -1000, 1000, 1, "px"),
      number("radius", "Flow Radius", 260, 1, 4000, 1, "px"),
      percent("blend", "Blend", 100),
    ],
  },
  {
    type: "griddler",
    name: "CC Griddler",
    category: "Distort",
    description: "Transform image tiles independently in a single ordered UV operation.",
    execution: "fused-pixel",
    parameters: [
      number("tileWidth", "Tile Width", 160, 2, 2000, 1, "px"),
      number("tileHeight", "Tile Height", 160, 2, 2000, 1, "px"),
      angle("rotation", "Tile Rotation", 0),
      number("scale", "Tile Scale", 100, 1, 1000, 0.1, "%"),
      number("offsetX", "Grid Offset X", 0, -4000, 4000, 1, "px"),
      number("offsetY", "Grid Offset Y", 0, -4000, 4000, 1, "px"),
      percent("blend", "Blend", 100),
    ],
  },
  {
    type: "power-pin",
    name: "CC Power Pin",
    category: "Distort",
    description:
      "Perspective-aware four-corner pinning with an animatable vertical projection curve.",
    execution: "fused-pixel",
    parameters: [
      point("upperLeftX", "Upper Left X", 0),
      point("upperLeftY", "Upper Left Y", 0),
      point("upperRightX", "Upper Right X", 100),
      point("upperRightY", "Upper Right Y", 0),
      point("lowerLeftX", "Lower Left X", 0),
      point("lowerLeftY", "Lower Left Y", 100),
      point("lowerRightX", "Lower Right X", 100),
      point("lowerRightY", "Lower Right Y", 100),
      number("perspective", "Perspective", 1, 0.1, 4, 0.01),
      percent("blend", "Blend", 100),
    ],
  },
  {
    type: "ripple-pulse",
    name: "CC Ripple Pulse",
    category: "Distort",
    description: "Emit a damped, time-addressable radial pulse from an arbitrary point.",
    execution: "fused-pixel",
    parameters: [
      point("centerX", "Center X", 50),
      point("centerY", "Center Y", 50),
      number("radius", "Pulse Radius", 280, 0, 4000, 1, "px"),
      number("waveWidth", "Wave Width", 80, 1, 2000, 1, "px"),
      number("amplitude", "Amplitude", 28, -1000, 1000, 1, "px"),
      number("speed", "Speed", 1, -20, 20, 0.1),
      angle("phase", "Phase", 0),
      number("decay", "Decay", 1.2, 0, 16, 0.1),
      percent("blend", "Blend", 100),
    ],
  },
  {
    type: "slant",
    name: "CC Slant",
    category: "Distort",
    description: "Shear the image around a movable horizontal or vertical floor.",
    execution: "fused-pixel",
    parameters: [
      angle("slant", "Slant", 24),
      number("floor", "Floor", 50, -100, 200, 0.1, "%"),
      choice("axis", "Axis", ["Horizontal", "Vertical"]),
      percent("blend", "Blend", 100),
    ],
  },
  {
    type: "smear",
    name: "CC Smear",
    category: "Distort",
    description: "Drag a feathered circular region between two points without an extra pass.",
    execution: "fused-pixel",
    parameters: [
      point("fromX", "From X", 35),
      point("fromY", "From Y", 50),
      point("toX", "To X", 65),
      point("toY", "To Y", 50),
      number("radius", "Radius", 180, 1, 4000, 1, "px"),
      percent("amount", "Amount", 100),
      number("feather", "Feather", 60, 0, 1000, 1, "px"),
      percent("blend", "Blend", 100),
    ],
  },
  {
    type: "split",
    name: "CC Split",
    category: "Distort",
    description: "Separate both sides of an angled, feathered split line.",
    execution: "fused-pixel",
    parameters: [
      point("centerX", "Center X", 50),
      point("centerY", "Center Y", 50),
      angle("angle", "Split Angle", 0),
      number("distance", "Split Distance", 80, -2000, 2000, 1, "px"),
      number("feather", "Feather", 12, 0, 1000, 1, "px"),
      percent("blend", "Blend", 100),
    ],
  },
];
