import { angle, color, number, percent, toggle } from "./parameter-builders";
import type { EffectDefinition } from "./types";

export const ADDITIONAL_EFFECTS: EffectDefinition[] = [
  {
    type: "box-blur",
    name: "Fast Box Blur",
    category: "Blur & Sharpen",
    description: "Constant-cost cross-kernel blur for responsive previews.",
    execution: "fused-pixel",
    parameters: [number("radius", "Blur Radius", 12, 0, 500, 0.5, "px")],
  },
  {
    type: "camera-lens-blur",
    name: "Camera Lens Blur",
    category: "Blur & Sharpen",
    description: "Disk-sampled bokeh blur with controllable highlight gain.",
    execution: "fused-pixel",
    parameters: [
      number("radius", "Blur Radius", 18, 0, 500, 0.5, "px"),
      angle("rotation", "Blade Rotation", 0),
      number("highlightThreshold", "Highlight Threshold", 0.72, 0, 4, 0.01),
      number("highlightGain", "Highlight Gain", 1.25, 0, 12, 0.05),
    ],
  },
  {
    type: "change-to-color",
    name: "Change to Color",
    category: "Color Correction",
    description: "Replace a selected color range while optionally preserving source luminance.",
    execution: "fused-pixel",
    parameters: [
      color("fromColor", "From", 0x3d65ff),
      color("toColor", "To", 0xff4fa7),
      number("tolerance", "Tolerance", 0.22, 0, 1.732, 0.005),
      number("softness", "Softness", 0.12, 0, 1, 0.005),
      toggle("preserveLuminance", "Preserve Luminance"),
    ],
  },
  {
    type: "leave-color",
    name: "Leave Color",
    category: "Color Correction",
    description: "Preserve one color range while desaturating the rest of the image.",
    execution: "fused-pixel",
    parameters: [
      color("color", "Color to Leave", 0xff3b72),
      number("tolerance", "Tolerance", 0.24, 0, 1.732, 0.005),
      number("softness", "Edge Softness", 0.16, 0, 1, 0.005),
      percent("amount", "Amount to Decolor", 100),
    ],
  },
  {
    type: "extract",
    name: "Extract",
    category: "Keying",
    description: "Build an alpha matte from a controllable luminance interval.",
    execution: "fused-pixel",
    parameters: [
      number("blackPoint", "Black Point", 0.12, 0, 1, 0.001),
      number("whitePoint", "White Point", 0.88, 0, 1, 0.001),
      number("softness", "Softness", 0.04, 0, 0.5, 0.001),
      toggle("invert", "Invert Matte", 0),
    ],
  },
  {
    type: "roughen-edges",
    name: "Roughen Edges",
    category: "Stylize",
    description: "Fractal alpha erosion with deterministic timeline evolution.",
    execution: "fused-pixel",
    parameters: [
      number("border", "Border", 12, 0, 256, 0.5, "px"),
      number("scale", "Scale", 80, 1, 2000, 1, "px"),
      number("complexity", "Complexity", 3, 1, 5, 1),
      number("evolution", "Evolution", 0, -1000, 1000, 0.1),
      number("sharpness", "Edge Sharpness", 0.15, 0.001, 1, 0.005),
    ],
  },
  {
    type: "light-burst",
    name: "CC Light Burst 2.5",
    category: "Generate",
    description: "Radial light streaks sampled toward a movable source point.",
    execution: "fused-pixel",
    parameters: [
      percent("centerX", "Center X", 50),
      percent("centerY", "Center Y", 50),
      number("rayLength", "Ray Length", 160, 0, 4000, 1, "px"),
      number("intensity", "Intensity", 1.4, 0, 20, 0.05),
      percent("blend", "Blend With Original", 100),
      color("color", "Ray Color", 0x9ddcff),
    ],
  },
  {
    type: "radial-shadow",
    name: "Radial Shadow",
    category: "Perspective",
    description: "Project a soft source-alpha shadow away from a movable light point.",
    execution: "fused-pixel",
    parameters: [
      percent("centerX", "Light X", 50),
      percent("centerY", "Light Y", 35),
      number("distance", "Projection Distance", 48, 0, 2000, 1, "px"),
      percent("opacity", "Opacity", 55),
      number("softness", "Softness", 18, 0, 500, 0.5, "px"),
      color("color", "Shadow Color", 0x08101f),
    ],
  },
];
