import { angle, choice, color, number, percent } from "./parameter-builders";
import type { EffectDefinition } from "./types";

export const AE_PERSPECTIVE_EFFECTS: EffectDefinition[] = [
  {
    type: "spherize",
    name: "Spherize",
    category: "Distort",
    description: "Project pixels through a configurable spherical bulge or pinch region.",
    execution: "fused-pixel",
    parameters: [
      percent("centerX", "Center X", 50),
      percent("centerY", "Center Y", 50),
      number("radius", "Radius", 320, 0, 4000, 1, "px"),
      percent("amount", "Amount", 75),
    ],
  },
  {
    type: "optics-compensation",
    name: "Optics Compensation",
    category: "Distort",
    description: "Correct or introduce wide-angle barrel and pincushion lens distortion.",
    execution: "fused-pixel",
    parameters: [
      number("fieldOfView", "Field of View", 55, 0, 180, 0.5, "°"),
      choice("direction", "Distortion", ["Correct", "Reverse"]),
      percent("centerX", "View Center X", 50),
      percent("centerY", "View Center Y", 50),
      number("scale", "View Scale", 100, 1, 400, 0.1, "%"),
    ],
  },
  {
    type: "bend-it",
    name: "CC Bend It",
    category: "Distort",
    description: "Bend a layer along a user-defined axis with sinusoidal continuity.",
    execution: "fused-pixel",
    parameters: [
      percent("startX", "Start X", 50),
      percent("startY", "Start Y", 20),
      percent("endX", "End X", 50),
      percent("endY", "End Y", 80),
      number("bend", "Bend", 120, -2000, 2000, 1, "px"),
    ],
  },
  {
    type: "cylinder",
    name: "CC Cylinder",
    category: "Perspective",
    description: "Wrap the source around a cylindrical projection with rotation and curvature.",
    execution: "fused-pixel",
    parameters: [
      percent("centerX", "Center X", 50),
      percent("centerY", "Center Y", 50),
      number("radius", "Radius", 480, 1, 8000, 1, "px"),
      angle("rotation", "Rotation", 0),
      percent("curvature", "Curvature", 100),
    ],
  },
  {
    type: "sphere",
    name: "CC Sphere",
    category: "Perspective",
    description: "Map the source onto a spherical projection with longitudinal rotation.",
    execution: "fused-pixel",
    parameters: [
      percent("centerX", "Center X", 50),
      percent("centerY", "Center Y", 50),
      number("radius", "Radius", 420, 1, 8000, 1, "px"),
      angle("rotation", "Rotation Y", 0),
      percent("magnification", "Magnification", 100),
    ],
  },
  {
    type: "mesh-warp",
    name: "Mesh Warp",
    category: "Distort",
    description:
      "Animate a continuous procedural mesh using independent horizontal and vertical waves.",
    execution: "fused-pixel",
    parameters: [
      number("horizontal", "Horizontal Distortion", 32, -1000, 1000, 1, "px"),
      number("vertical", "Vertical Distortion", 32, -1000, 1000, 1, "px"),
      number("columns", "Columns", 4, 1, 32, 1),
      number("rows", "Rows", 4, 1, 32, 1),
      angle("phase", "Phase", 0),
      percent("blend", "Distortion Amount", 100),
    ],
  },
  {
    type: "warp",
    name: "Warp",
    category: "Distort",
    description: "Apply Arc, Flag, Wave, or Fisheye deformation with cross-axis distortion.",
    execution: "fused-pixel",
    parameters: [
      choice("style", "Warp Style", ["Arc", "Flag", "Wave", "Fisheye"]),
      number("bend", "Bend", 35, -100, 100, 0.5, "%"),
      number("horizontal", "Horizontal Distortion", 0, -100, 100, 0.5, "%"),
      number("vertical", "Vertical Distortion", 0, -100, 100, 0.5, "%"),
      angle("axis", "Axis Rotation", 0),
    ],
  },
  {
    type: "page-turn",
    name: "CC Page Turn",
    category: "Transition",
    description: "Curl the layer around an angled fold with a shaded configurable back face.",
    execution: "fused-pixel",
    parameters: [
      percent("completion", "Fold Position", 45),
      angle("angle", "Fold Angle", -28),
      number("radius", "Fold Radius", 90, 1, 1000, 1, "px"),
      color("backColor", "Back Page Color", 0x596786),
      percent("backOpacity", "Back Page Opacity", 85),
    ],
  },
];
