import { angle, choice, number, percent, toggle } from "./parameter-builders";
import type { EffectDefinition } from "./types";

export const PROFESSIONAL_COLOR_EFFECTS: EffectDefinition[] = [
  {
    type: "asc-cdl",
    name: "ASC CDL",
    category: "Color Correction",
    description:
      "Apply the standard slope, offset, power, and saturation color decision transform.",
    execution: "fused-pixel",
    parameters: [
      number("slopeR", "Slope Red", 1, 0, 8, 0.01),
      number("slopeG", "Slope Green", 1, 0, 8, 0.01),
      number("slopeB", "Slope Blue", 1, 0, 8, 0.01),
      number("offsetR", "Offset Red", 0, -1, 1, 0.005),
      number("offsetG", "Offset Green", 0, -1, 1, 0.005),
      number("offsetB", "Offset Blue", 0, -1, 1, 0.005),
      number("powerR", "Power Red", 1, 0.05, 8, 0.01),
      number("powerG", "Power Green", 1, 0.05, 8, 0.01),
      number("powerB", "Power Blue", 1, 0.05, 8, 0.01),
      number("saturation", "Saturation", 1, 0, 4, 0.01),
    ],
  },
  {
    type: "rgb-lift-gamma-gain",
    name: "RGB Lift / Gamma / Gain",
    category: "Color Correction",
    description: "Grade each RGB channel independently across lift, gamma, and gain ranges.",
    execution: "fused-pixel",
    parameters: [
      number("liftR", "Lift Red", 0, -1, 1, 0.005),
      number("liftG", "Lift Green", 0, -1, 1, 0.005),
      number("liftB", "Lift Blue", 0, -1, 1, 0.005),
      number("gammaR", "Gamma Red", 1, 0.05, 8, 0.01),
      number("gammaG", "Gamma Green", 1, 0.05, 8, 0.01),
      number("gammaB", "Gamma Blue", 1, 0.05, 8, 0.01),
      number("gainR", "Gain Red", 1, 0, 8, 0.01),
      number("gainG", "Gain Green", 1, 0, 8, 0.01),
      number("gainB", "Gain Blue", 1, 0, 8, 0.01),
      number("master", "Master Gain", 1, 0, 8, 0.01),
    ],
  },
  {
    type: "log-wheels",
    name: "Log Wheels",
    category: "Color Correction",
    description: "Tint shadows, midtones, and highlights with overlapping logarithmic ranges.",
    execution: "fused-pixel",
    parameters: [
      angle("shadowHue", "Shadow Hue", 220),
      number("shadowAmount", "Shadow Amount", 0, -1, 1, 0.01),
      angle("midtoneHue", "Midtone Hue", 30),
      number("midtoneAmount", "Midtone Amount", 0, -1, 1, 0.01),
      angle("highlightHue", "Highlight Hue", 45),
      number("highlightAmount", "Highlight Amount", 0, -1, 1, 0.01),
      number("shadowRange", "Shadow Range", 0.32, 0.05, 0.8, 0.01),
      number("highlightRange", "Highlight Range", 0.68, 0.2, 0.95, 0.01),
      number("saturation", "Saturation", 1, 0, 4, 0.01),
    ],
  },
  {
    type: "hsl-secondary",
    name: "HSL Secondary",
    category: "Color Correction",
    description: "Qualify a hue, saturation, and luminance range for isolated correction.",
    execution: "fused-pixel",
    parameters: [
      angle("hueCenter", "Hue Center", 210),
      angle("hueRange", "Hue Range", 35),
      number("saturationMin", "Saturation Minimum", 0.15, 0, 1, 0.005),
      number("saturationMax", "Saturation Maximum", 1, 0, 1, 0.005),
      number("luminanceMin", "Luminance Minimum", 0, 0, 1, 0.005),
      number("luminanceMax", "Luminance Maximum", 1, 0, 1, 0.005),
      number("softness", "Key Softness", 0.1, 0, 1, 0.005),
      angle("hueShift", "Hue Shift", 0),
      number("saturation", "Saturation", 1, 0, 4, 0.01),
      number("lightness", "Lightness", 0, -1, 1, 0.01),
      toggle("invert", "Invert Qualification", 0),
    ],
  },
  {
    type: "highlight-recovery",
    name: "Highlight Recovery",
    category: "Color Correction",
    description: "Reconstruct clipped highlights with chroma-preserving soft rolloff.",
    execution: "fused-pixel",
    parameters: [
      number("threshold", "Recovery Threshold", 0.82, 0.01, 8, 0.01),
      percent("strength", "Recovery Strength", 75),
      number("rolloff", "Rolloff", 2.5, 0.1, 16, 0.1),
      percent("saturation", "Recovered Saturation", 65),
      percent("blend", "Blend With Original", 100),
    ],
  },
  {
    type: "gamut-compressor",
    name: "Gamut Compressor",
    category: "Color Correction",
    description: "Compress extreme chroma into a bounded display gamut without hard clipping.",
    execution: "fused-pixel",
    parameters: [
      number("threshold", "Chroma Threshold", 0.72, 0, 4, 0.01),
      number("limit", "Chroma Limit", 1, 0.01, 8, 0.01),
      number("power", "Compression Power", 2, 0.1, 16, 0.1),
      toggle("preserveLuminance", "Preserve Luminance", 1),
      percent("blend", "Blend With Original", 100),
    ],
  },
  {
    type: "false-color",
    name: "False Color",
    category: "Color Correction",
    description: "Visualize scene luminance as calibrated IRE or exposure-stop zones.",
    execution: "fused-pixel",
    parameters: [
      choice("mode", "Scale", ["Exposure Stops", "IRE Zones"]),
      number("middleGray", "Middle Gray", 0.18, 0.01, 1, 0.005),
      number("range", "Exposure Range", 6, 1, 16, 0.5, "stops"),
      percent("opacity", "Overlay Opacity", 100),
    ],
  },
  {
    type: "film-print-density",
    name: "Film Print Density",
    category: "Looks",
    description:
      "Apply subtractive cyan, magenta, yellow, and master print density with soft clipping.",
    execution: "fused-pixel",
    parameters: [
      number("cyan", "Cyan Density", 0, -1, 1, 0.005),
      number("magenta", "Magenta Density", 0, -1, 1, 0.005),
      number("yellow", "Yellow Density", 0, -1, 1, 0.005),
      number("density", "Master Density", 0, -2, 2, 0.01),
      number("contrast", "Print Contrast", 1.08, 0, 4, 0.01),
      number("softClip", "Highlight Soft Clip", 0.85, 0.05, 8, 0.01),
      percent("blend", "Blend With Original", 100),
    ],
  },
];
