import { angle, choice, color, number, percent } from "./parameter-builders";
import type { EffectDefinition } from "./types";

export const DRAW_GENERATOR_EFFECTS: EffectDefinition[] = [
  {
    type: "ellipse",
    name: "Ellipse",
    category: "Generate",
    description: "Draw an antialiased, rotated ellipse as a ring or filled HDR shape.",
    execution: "fused-pixel",
    parameters: [
      percent("centerX", "Center X", 50),
      percent("centerY", "Center Y", 50),
      number("width", "Width", 480, 1, 8000, 1, "px"),
      number("height", "Height", 280, 1, 8000, 1, "px"),
      angle("rotation", "Rotation", 0),
      number("thickness", "Thickness", 12, 0.25, 1000, 0.25, "px"),
      number("feather", "Feather", 2, 0, 500, 0.25, "px"),
      choice("mode", "Mode", ["Ring", "Filled"]),
      color("color", "Color", 0x65bdff),
      percent("opacity", "Opacity", 100),
      percent("blend", "Blend With Original", 100),
    ],
  },
  {
    type: "stroke",
    name: "Stroke",
    category: "Generate",
    description: "Render a partially revealed quadratic path with GPU antialiasing.",
    execution: "fused-pixel",
    parameters: [
      percent("startX", "Start X", 20),
      percent("startY", "Start Y", 65),
      percent("controlX", "Control X", 50),
      percent("controlY", "Control Y", 20),
      percent("endX", "End X", 80),
      percent("endY", "End Y", 65),
      number("width", "Brush Size", 14, 0.25, 1000, 0.25, "px"),
      number("feather", "Feather", 3, 0, 500, 0.25, "px"),
      percent("start", "Start", 0),
      percent("end", "End", 100),
      color("color", "Color", 0x77d8ff),
      percent("opacity", "Opacity", 100),
      percent("blend", "Blend With Original", 100),
    ],
  },
  {
    type: "vegas",
    name: "Vegas",
    category: "Generate",
    description: "Trace the alpha boundary with animated segmented neon strokes.",
    execution: "fused-pixel",
    parameters: [
      number("edgeRadius", "Edge Radius", 2, 0.5, 64, 0.5, "px"),
      number("segmentLength", "Segment Length", 48, 2, 1000, 1, "px"),
      angle("rotation", "Rotation", 0),
      number("width", "Stroke Width", 6, 0.25, 128, 0.25, "px"),
      color("color", "Color", 0xff4fd8),
      percent("opacity", "Opacity", 100),
      percent("blend", "Blend With Original", 100),
    ],
  },
  {
    type: "scribble",
    name: "Scribble",
    category: "Generate",
    description: "Generate animated hand-drawn hatch lines with deterministic timeline noise.",
    execution: "fused-pixel",
    parameters: [
      number("spacing", "Spacing", 32, 2, 1000, 1, "px"),
      angle("angle", "Angle", -25),
      number("width", "Stroke Width", 3, 0.25, 128, 0.25, "px"),
      number("wiggle", "Wiggle", 12, 0, 500, 0.5, "px"),
      number("evolution", "Evolution", 0.5, -20, 20, 0.1),
      color("color", "Color", 0xf8f1d8),
      percent("opacity", "Opacity", 80),
      percent("blend", "Blend With Original", 100),
    ],
  },
  {
    type: "write-on",
    name: "Write-on",
    category: "Generate",
    description: "Reveal a feathered brush stroke between two animatable points.",
    execution: "fused-pixel",
    parameters: [
      percent("startX", "Start X", 20),
      percent("startY", "Start Y", 50),
      percent("endX", "End X", 80),
      percent("endY", "End Y", 50),
      percent("progress", "Progress", 60),
      number("width", "Brush Size", 18, 0.25, 1000, 0.25, "px"),
      number("feather", "Feather", 4, 0, 500, 0.25, "px"),
      color("color", "Color", 0xffc857),
      percent("opacity", "Opacity", 100),
      percent("blend", "Blend With Original", 100),
    ],
  },
  {
    type: "eyedropper-fill",
    name: "Eyedropper Fill",
    category: "Generate",
    description: "Replace colors similar to an animatable sample point with a chosen HDR fill.",
    execution: "fused-pixel",
    parameters: [
      percent("sampleX", "Sample Point X", 50),
      percent("sampleY", "Sample Point Y", 50),
      number("tolerance", "Tolerance", 0.18, 0, 1.732, 0.005),
      number("softness", "Softness", 0.08, 0, 1, 0.005),
      color("color", "New Color", 0x5fd7ff),
      percent("opacity", "Opacity", 100),
      percent("blend", "Blend With Original", 100),
    ],
  },
  {
    type: "paint-bucket",
    name: "Paint Bucket",
    category: "Generate",
    description: "Apply a bounded, soft color-similarity fill around an animatable seed point.",
    execution: "fused-pixel",
    parameters: [
      percent("seedX", "Fill Point X", 50),
      percent("seedY", "Fill Point Y", 50),
      number("tolerance", "Tolerance", 0.2, 0, 1.732, 0.005),
      number("softness", "Softness", 0.08, 0, 1, 0.005),
      number("radius", "Fill Radius", 720, 1, 8000, 1, "px"),
      color("color", "Fill Color", 0xff6f5f),
      percent("opacity", "Opacity", 100),
      percent("blend", "Blend With Original", 100),
    ],
  },
];
