import { angle, choice, color, number, percent, toggle } from "./parameter-builders";
import type { EffectDefinition } from "./types";

export const ENVIRONMENT_EFFECTS: EffectDefinition[] = [
  {
    type: "offset",
    name: "Offset",
    category: "Distort",
    description: "Shift the source in composition pixels with optional seamless edge wrapping.",
    execution: "fused-pixel",
    parameters: [
      number("shiftX", "Shift Center To X", 0, -8000, 8000, 1, "px"),
      number("shiftY", "Shift Center To Y", 0, -8000, 8000, 1, "px"),
      toggle("wrapEdges", "Wrap Around", 1),
    ],
  },
  {
    type: "magnify",
    name: "Magnify",
    category: "Distort",
    description: "Magnify a feathered circular or square region around an animatable center.",
    execution: "fused-pixel",
    parameters: [
      percent("centerX", "Center X", 50),
      percent("centerY", "Center Y", 50),
      number("magnification", "Magnification", 2, 0.05, 32, 0.05),
      number("size", "Size", 280, 1, 4000, 1, "px"),
      number("feather", "Feather", 48, 0, 1000, 1, "px"),
      choice("shape", "Shape", ["Circle", "Square"]),
    ],
  },
  {
    type: "ripple",
    name: "Ripple",
    category: "Distort",
    description: "Displace pixels along animated concentric waves with radial falloff.",
    execution: "fused-pixel",
    parameters: [
      percent("centerX", "Center X", 50),
      percent("centerY", "Center Y", 50),
      number("height", "Wave Height", 18, -500, 500, 0.5, "px"),
      number("width", "Wave Width", 120, 1, 2000, 1, "px"),
      number("radius", "Radius", 600, 1, 8000, 1, "px"),
      number("phase", "Phase", 0, -1000, 1000, 0.01),
      number("speed", "Wave Speed", 1, -20, 20, 0.05),
    ],
  },
  {
    type: "corner-pin",
    name: "Corner Pin",
    category: "Distort",
    description: "Warp the source through four independently animatable composition-space corners.",
    execution: "fused-pixel",
    parameters: [
      percent("upperLeftX", "Upper Left X", 0),
      percent("upperLeftY", "Upper Left Y", 0),
      percent("upperRightX", "Upper Right X", 100),
      percent("upperRightY", "Upper Right Y", 0),
      percent("lowerLeftX", "Lower Left X", 0),
      percent("lowerLeftY", "Lower Left Y", 100),
      percent("lowerRightX", "Lower Right X", 100),
      percent("lowerRightY", "Lower Right Y", 100),
      percent("blend", "Blend With Original", 100),
    ],
  },
  {
    type: "lens-flare",
    name: "Lens Flare",
    category: "Generate",
    description: "Synthesize an HDR optical flare with halo, ring, streak, and lens ghosts.",
    execution: "fused-pixel",
    parameters: [
      percent("centerX", "Flare Center X", 58),
      percent("centerY", "Flare Center Y", 38),
      number("brightness", "Flare Brightness", 1.8, 0, 32, 0.05),
      number("scale", "Lens Scale", 180, 1, 4000, 1, "px"),
      angle("angle", "Streak Angle", 0),
      choice("lensType", "Lens Type", ["Prime", "Zoom", "Anamorphic"]),
      color("color", "Tint", 0xa8cfff),
      percent("blend", "Blend With Original", 100),
    ],
  },
  {
    type: "cell-pattern",
    name: "Cell Pattern",
    category: "Generate",
    description: "Generate animated Worley cells as plates, crystals, or soft bubbles.",
    execution: "fused-pixel",
    parameters: [
      number("cellSize", "Cell Size", 120, 2, 2000, 1, "px"),
      number("contrast", "Contrast", 1.4, 0, 16, 0.05),
      number("evolution", "Evolution", 0, -1000, 1000, 0.1),
      choice("pattern", "Pattern", ["Plates", "Crystals", "Bubbles"]),
      toggle("invert", "Invert", 0),
      color("color1", "Cell Color", 0x102656),
      color("color2", "Border Color", 0x6edaff),
      percent("blend", "Blend With Original", 100),
    ],
  },
  {
    type: "rainfall",
    name: "CC Rainfall",
    category: "Simulation",
    description: "Render a deterministic, timeline-addressable field of motion-streaked rain.",
    execution: "fused-pixel",
    parameters: [
      number("density", "Drops", 1, 0.05, 8, 0.05),
      number("speed", "Speed", 900, -4000, 4000, 10, "px/s"),
      angle("direction", "Direction", 78),
      number("length", "Drop Length", 48, 1, 500, 1, "px"),
      number("width", "Drop Width", 1.5, 0.25, 32, 0.25, "px"),
      number("seed", "Random Seed", 1, 0, 10000, 1),
      color("color", "Drop Color", 0xa8d8ff),
      percent("opacity", "Opacity", 70),
    ],
  },
  {
    type: "snowfall",
    name: "CC Snowfall",
    category: "Simulation",
    description: "Render softly antialiased snow with wind, turbulence, and depth variation.",
    execution: "fused-pixel",
    parameters: [
      number("density", "Flakes", 1, 0.05, 8, 0.05),
      number("speed", "Fall Speed", 140, -2000, 2000, 5, "px/s"),
      number("size", "Flake Size", 5, 0.5, 100, 0.25, "px"),
      number("wind", "Wind", 55, -1000, 1000, 1, "px/s"),
      number("turbulence", "Turbulence", 24, 0, 500, 1, "px"),
      number("seed", "Random Seed", 1, 0, 10000, 1),
      color("color", "Flake Color", 0xe8f4ff),
      percent("opacity", "Opacity", 85),
    ],
  },
];
