import { angle, choice, color, number, percent } from "./parameter-builders";
import type { EffectDefinition } from "./types";

export const GENERATOR_EFFECTS: EffectDefinition[] = [
  {
    type: "multi-stop-gradient",
    name: "Multi-Stop Gradient",
    category: "Generate",
    description: "Five animated color stops between two points, preserving source alpha.",
    execution: "fused-pixel",
    parameters: [
      number("startX", "Starting Point X", 0, -200, 300, 0.1, "%"),
      number("startY", "Starting Point Y", 50, -200, 300, 0.1, "%"),
      number("endX", "Ending Point X", 100, -200, 300, 0.1, "%"),
      number("endY", "Ending Point Y", 50, -200, 300, 0.1, "%"),
      color("color1", "Start Color", 0x38cddd),
      color("color2", "Color 2", 0xd9f3f2),
      percent("position2", "Position 2", 25),
      color("color3", "Color 3", 0xe757a4),
      percent("position3", "Position 3", 50),
      color("color4", "Color 4", 0x0784d5),
      percent("position4", "Position 4", 80),
      color("color5", "End Color", 0x021a2b),
      choice("mapping", "Mapping", ["Linear", "Radial", "Angular"], 0),
      choice("interpolation", "Interpolation", ["Linear", "Smooth"], 0),
      percent("blend", "Blend With Original", 100),
    ],
  },
  {
    type: "ball-action",
    name: "CC Ball Action",
    category: "Simulation",
    description: "Rebuild the source from GPU-sampled spherical cells with animated scatter.",
    execution: "fused-pixel",
    parameters: [
      number("gridSize", "Grid Spacing", 36, 4, 512, 1, "px"),
      percent("ballSize", "Ball Size", 72),
      number("scatter", "Scatter", 0, 0, 500, 0.5, "px"),
      angle("twist", "Twist Angle", 0),
      percent("blend", "Blend With Original", 100),
    ],
  },
  {
    type: "hex-tile",
    name: "CC HexTile",
    category: "Distort",
    description: "Quantize the image into a rotatable hexagonal sampling lattice.",
    execution: "fused-pixel",
    parameters: [
      number("tileSize", "Tile Size", 64, 4, 1024, 1, "px"),
      percent("centerX", "Center X", 50),
      percent("centerY", "Center Y", 50),
      angle("rotation", "Rotation", 0),
      percent("scale", "Scale", 100),
      percent("blend", "Blend With Original", 100),
    ],
  },
  {
    type: "beam",
    name: "Beam",
    category: "Generate",
    description: "Draw a soft, HDR line between two animatable points with a color gradient.",
    execution: "fused-pixel",
    parameters: [
      percent("startX", "Starting Point X", 25),
      percent("startY", "Starting Point Y", 50),
      percent("endX", "Ending Point X", 75),
      percent("endY", "Ending Point Y", 50),
      number("thickness", "Starting Thickness", 12, 0.25, 500, 0.25, "px"),
      number("softness", "Softness", 8, 0, 500, 0.25, "px"),
      number("intensity", "Intensity", 2, 0, 32, 0.05),
      color("startColor", "Inside Color", 0xe8fbff),
      color("endColor", "Outside Color", 0x3293ff),
      percent("blend", "Blend With Original", 100),
    ],
  },
  {
    type: "radio-waves",
    name: "Radio Waves",
    category: "Generate",
    description: "Emit antialiased concentric waves with timeline-driven phase animation.",
    execution: "fused-pixel",
    parameters: [
      percent("centerX", "Producer X", 50),
      percent("centerY", "Producer Y", 50),
      number("frequency", "Frequency", 6, 0.1, 64, 0.1),
      number("speed", "Expansion Speed", 120, -2000, 2000, 1, "px/s"),
      number("width", "Stroke Width", 4, 0.25, 256, 0.25, "px"),
      number("intensity", "Intensity", 1.5, 0, 32, 0.05),
      percent("fade", "Fade Out", 65),
      color("color", "Stroke Color", 0x56c8ff),
      percent("blend", "Blend With Original", 100),
    ],
  },
  {
    type: "advanced-lightning",
    name: "Advanced Lightning",
    category: "Generate",
    description: "Generate a deterministic fractal lightning bolt with an HDR halo.",
    execution: "fused-pixel",
    parameters: [
      percent("startX", "Origin X", 28),
      percent("startY", "Origin Y", 20),
      percent("endX", "Direction X", 72),
      percent("endY", "Direction Y", 80),
      number("amplitude", "Conductivity State", 48, 0, 1000, 1, "px"),
      number("frequency", "Complexity", 8, 1, 64, 1),
      number("evolution", "Evolution", 0, -1000, 1000, 0.1),
      number("thickness", "Core Radius", 2.5, 0.25, 128, 0.25, "px"),
      number("glow", "Glow Radius", 22, 0, 500, 0.5, "px"),
      color("color", "Core Color", 0xbde8ff),
      percent("blend", "Blend With Original", 100),
    ],
  },
  {
    type: "circle",
    name: "Circle",
    category: "Generate",
    description: "Render a GPU-antialiased ring or filled disk in composition space.",
    execution: "fused-pixel",
    parameters: [
      percent("centerX", "Center X", 50),
      percent("centerY", "Center Y", 50),
      number("radius", "Radius", 240, 0, 4000, 1, "px"),
      number("thickness", "Edge", 12, 0.25, 1000, 0.25, "px"),
      number("feather", "Feather", 2, 0, 500, 0.25, "px"),
      choice("mode", "Edge", ["Ring", "Filled"]),
      color("color", "Color", 0x52a8ff),
      percent("opacity", "Opacity", 100),
      percent("blend", "Blend With Original", 100),
    ],
  },
  {
    type: "star-burst",
    name: "CC Star Burst",
    category: "Generate",
    description: "Create a radial field of tapered HDR rays around an animatable center.",
    execution: "fused-pixel",
    parameters: [
      percent("centerX", "Center X", 50),
      percent("centerY", "Center Y", 50),
      number("rays", "Rays", 24, 2, 256, 1),
      number("radius", "Radius", 420, 1, 4000, 1, "px"),
      angle("rotation", "Rotation", 0),
      number("sharpness", "Ray Sharpness", 12, 0.5, 128, 0.5),
      number("intensity", "Intensity", 1.2, 0, 32, 0.05),
      color("color", "Color", 0x70b7ff),
      percent("blend", "Blend With Original", 100),
    ],
  },
  {
    type: "polar-coordinates",
    name: "Polar Coordinates",
    category: "Distort",
    description: "Continuously remap rectangular coordinates to polar space or back again.",
    execution: "fused-pixel",
    parameters: [
      choice("mode", "Type of Conversion", ["Rect to Polar", "Polar to Rect"]),
      percent("interpolation", "Interpolation", 100),
      percent("centerX", "Center X", 50),
      percent("centerY", "Center Y", 50),
      angle("rotation", "Rotation", 0),
    ],
  },
];
