import { angle, choice, color, number, percent, toggle } from "./parameter-builders";
import type { EffectDefinition } from "./types";

export const MATTE_REFINE_EFFECTS: EffectDefinition[] = [
  {
    type: "refine-hard-matte",
    name: "Refine Hard Matte",
    category: "Matte",
    description:
      "Tighten hard alpha edges with edge shift, contrast, clipping, and decontamination.",
    execution: "multi-pass",
    parameters: [
      number("radius", "Edge Radius", 2, 0.5, 128, 0.5, "px"),
      number("edgeShift", "Shift Edge", 0, -100, 100, 0.5, "%"),
      number("contrast", "Edge Contrast", 1.4, 0.1, 8, 0.05),
      number("clipBlack", "Clip Black", 0.03, 0, 1, 0.005),
      number("clipWhite", "Clip White", 0.97, 0, 1, 0.005),
      percent("decontaminate", "Decontaminate Edge Colors", 35),
    ],
  },
  {
    type: "refine-soft-matte",
    name: "Refine Soft Matte",
    category: "Matte",
    description: "Smooth translucent alpha edges while retaining fine soft detail.",
    execution: "multi-pass",
    parameters: [
      number("radius", "Edge Radius", 4, 0.5, 256, 0.5, "px"),
      percent("smoothness", "Smoothness", 55),
      number("edgeShift", "Shift Edge", 0, -100, 100, 0.5, "%"),
      number("contrast", "Edge Contrast", 1, 0.1, 8, 0.05),
      percent("decontaminate", "Decontaminate Edge Colors", 25),
      percent("amount", "Refine Amount", 100),
    ],
  },
  {
    type: "matte-feather",
    name: "Matte Feather",
    category: "Matte",
    description: "Feather and expand or contract alpha with gamma-shaped falloff.",
    execution: "multi-pass",
    parameters: [
      number("radius", "Feather Radius", 12, 0.5, 500, 0.5, "px"),
      number("expand", "Expand / Contract", 0, -100, 100, 0.5, "%"),
      number("gamma", "Feather Gamma", 1, 0.05, 8, 0.01),
      percent("opacity", "Matte Opacity", 100),
      toggle("invert", "Invert Matte", 0),
    ],
  },
  {
    type: "matte-cleanup",
    name: "Matte Cleanup",
    category: "Matte",
    description: "Clip, denoise, and fill small holes in a generated alpha matte.",
    execution: "multi-pass",
    parameters: [
      number("clipBlack", "Clip Black", 0.04, 0, 1, 0.005),
      number("clipWhite", "Clip White", 0.96, 0, 1, 0.005),
      number("gamma", "Gamma", 1, 0.05, 8, 0.01),
      number("radius", "Cleanup Radius", 2, 0.5, 128, 0.5, "px"),
      percent("reduceChatter", "Reduce Chatter", 45),
      percent("fillHoles", "Fill Holes", 25),
      toggle("invert", "Invert Matte", 0),
    ],
  },
  {
    type: "edge-decontaminate",
    name: "Edge Color Decontaminate",
    category: "Keying",
    description: "Remove a known screen or background color from translucent edge pixels.",
    execution: "multi-pass",
    parameters: [
      color("backgroundColor", "Contamination Color", 0x00b96b),
      percent("amount", "Decontamination Amount", 70),
      number("radius", "Edge Radius", 3, 0.5, 128, 0.5, "px"),
      number("edgeContrast", "Edge Contrast", 1, 0.1, 8, 0.05),
      toggle("preserveLuminance", "Preserve Luminance", 1),
    ],
  },
  {
    type: "light-wrap",
    name: "Light Wrap",
    category: "Keying",
    description: "Blend a tinted light wrap into the interior edge of keyed alpha.",
    execution: "multi-pass",
    parameters: [
      color("color", "Wrap Color", 0x9fd9ff),
      number("size", "Wrap Size", 18, 0.5, 500, 0.5, "px"),
      number("intensity", "Intensity", 1, 0, 8, 0.01),
      percent("edgeWidth", "Edge Width", 65),
      choice("mode", "Composite", ["Screen", "Add", "Normal"]),
      percent("opacity", "Opacity", 75),
    ],
  },
  {
    type: "alpha-bevel",
    name: "Alpha Bevel",
    category: "Matte",
    description: "Shade alpha edges with independent highlight and shadow colors.",
    execution: "multi-pass",
    parameters: [
      number("size", "Bevel Size", 5, 0.5, 128, 0.5, "px"),
      number("depth", "Depth", 1.2, 0, 8, 0.05),
      angle("angle", "Light Angle", 135),
      color("highlightColor", "Highlight", 0xffffff),
      percent("highlightOpacity", "Highlight Opacity", 70),
      color("shadowColor", "Shadow", 0x10172b),
      percent("shadowOpacity", "Shadow Opacity", 60),
    ],
  },
  {
    type: "alpha-erode-dilate",
    name: "Alpha Erode / Dilate",
    category: "Matte",
    description: "Expand or contract alpha using a bounded cross-neighborhood morphology pass.",
    execution: "multi-pass",
    parameters: [
      number("radius", "Radius", 3, 0.5, 256, 0.5, "px"),
      choice("operation", "Operation", ["Erode", "Dilate"]),
      percent("softness", "Softness", 15),
      number("iterations", "Iterations", 1, 1, 4, 1),
    ],
  },
];
