import { createId, type Effect } from "../core/types";
import type { EffectDefinition, EffectParameterDefinition } from "./types";

const number = (
  key: string,
  label: string,
  defaultValue: number,
  min: number,
  max: number,
  step = 1,
  unit = "",
): EffectParameterDefinition => ({
  key,
  label,
  kind: "number",
  defaultValue,
  min,
  max,
  step,
  unit,
});

const percent = (key: string, label: string, defaultValue: number) => ({
  ...number(key, label, defaultValue, 0, 100, 1, "%"),
  kind: "percent" as const,
});

const angle = (key: string, label: string, defaultValue: number) => ({
  ...number(key, label, defaultValue, -360, 360, 1, "°"),
  kind: "angle" as const,
});

const toggle = (key: string, label: string, defaultValue = 1): EffectParameterDefinition => ({
  key,
  label,
  kind: "toggle",
  defaultValue,
  min: 0,
  max: 1,
  step: 1,
});

const choice = (
  key: string,
  label: string,
  options: string[],
  defaultValue = 0,
): EffectParameterDefinition => ({
  key,
  label,
  kind: "choice",
  defaultValue,
  options,
  min: 0,
  max: options.length - 1,
  step: 1,
});

const color = (key: string, label: string, defaultValue: number): EffectParameterDefinition => ({
  key,
  label,
  kind: "color",
  defaultValue,
});

export const EFFECT_REGISTRY: EffectDefinition[] = [
  {
    type: "gaussian-blur",
    name: "Gaussian Blur",
    category: "Blur & Sharpen",
    description: "Separable high-quality GPU blur.",
    execution: "multi-pass",
    parameters: [
      number("radius", "Blurriness", 18, 0, 500, 0.5, "px"),
      toggle("repeatEdge", "Repeat Edge Pixels"),
    ],
  },
  {
    type: "kawase-blur",
    name: "Fast Kawase Blur",
    category: "Blur & Sharpen",
    description: "Multi-resolution realtime blur for large radii.",
    execution: "multi-pass",
    parameters: [
      number("radius", "Radius", 24, 0, 1000, 1, "px"),
      number("iterations", "Iterations", 4, 1, 12),
    ],
  },
  {
    type: "directional-blur",
    name: "Directional Blur",
    category: "Blur & Sharpen",
    description: "Blur along a configurable direction.",
    execution: "multi-pass",
    parameters: [
      number("length", "Blur Length", 24, 0, 500, 0.5, "px"),
      angle("direction", "Direction", 0),
    ],
  },
  {
    type: "radial-blur",
    name: "Radial Blur",
    category: "Blur & Sharpen",
    description: "Spin or zoom blur around a point.",
    execution: "fused-pixel",
    parameters: [
      number("amount", "Amount", 12, -100, 100, 0.5),
      choice("mode", "Type", ["Spin", "Zoom"]),
    ],
  },
  {
    type: "bilateral-blur",
    name: "Bilateral Surface Blur",
    category: "Blur & Sharpen",
    description: "Edge-aware blur preserving important detail.",
    execution: "compute",
    parameters: [
      number("radius", "Radius", 12, 0, 100, 0.5, "px"),
      number("threshold", "Threshold", 0.12, 0, 1, 0.01),
    ],
  },
  {
    type: "sharpen",
    name: "Unsharp Mask",
    category: "Blur & Sharpen",
    description: "High-frequency contrast enhancement.",
    execution: "multi-pass",
    parameters: [
      number("amount", "Amount", 60, 0, 500, 1, "%"),
      number("radius", "Radius", 1.5, 0.1, 100, 0.1, "px"),
      number("threshold", "Threshold", 0, 0, 255),
    ],
  },
  {
    type: "brightness-contrast",
    name: "Brightness & Contrast",
    category: "Color Correction",
    description: "GPU-fused tonal adjustment.",
    execution: "fused-pixel",
    parameters: [
      number("brightness", "Brightness", 0, -1, 1, 0.01),
      number("contrast", "Contrast", 1, 0, 3, 0.01),
    ],
  },
  {
    type: "exposure",
    name: "Exposure",
    category: "Color Correction",
    description: "Linear-light exposure and gamma.",
    execution: "fused-pixel",
    parameters: [
      number("exposure", "Exposure", 0, -10, 10, 0.05, "EV"),
      number("offset", "Offset", 0, -1, 1, 0.001),
      number("gamma", "Gamma", 1, 0.1, 10, 0.01),
    ],
  },
  {
    type: "hue-saturation",
    name: "Hue / Saturation",
    category: "Color Correction",
    description: "Perceptual hue, saturation, and lightness.",
    execution: "fused-pixel",
    parameters: [
      angle("hue", "Master Hue", 0),
      number("saturation", "Saturation", 1, 0, 3, 0.01),
      number("lightness", "Lightness", 0, -1, 1, 0.01),
    ],
  },
  {
    type: "levels",
    name: "Levels",
    category: "Color Correction",
    description: "Input, gamma, and output range mapping.",
    execution: "fused-pixel",
    parameters: [
      number("inputBlack", "Input Black", 0, 0, 1, 0.001),
      number("inputWhite", "Input White", 1, 0, 1, 0.001),
      number("gamma", "Gamma", 1, 0.1, 10, 0.01),
      number("outputBlack", "Output Black", 0, 0, 1, 0.001),
      number("outputWhite", "Output White", 1, 0, 1, 0.001),
    ],
  },
  {
    type: "curves",
    name: "Curves",
    category: "Color Correction",
    description: "Editable RGB and channel tone curves.",
    execution: "fused-pixel",
    parameters: [
      number("shadows", "Shadows", 0, -1, 1, 0.01),
      number("midtones", "Midtones", 0, -1, 1, 0.01),
      number("highlights", "Highlights", 0, -1, 1, 0.01),
    ],
  },
  {
    type: "vibrance",
    name: "Vibrance",
    category: "Color Correction",
    description: "Skin-safe adaptive saturation.",
    execution: "fused-pixel",
    parameters: [
      number("vibrance", "Vibrance", 0, -1, 1, 0.01),
      number("saturation", "Saturation", 1, 0, 3, 0.01),
    ],
  },
  {
    type: "tint",
    name: "Tint",
    category: "Color Correction",
    description: "Map luminance between two colors.",
    execution: "fused-pixel",
    parameters: [
      color("black", "Map Black To", 0x152446),
      color("white", "Map White To", 0xdce8ff),
      percent("amount", "Amount", 100),
    ],
  },
  {
    type: "color-balance",
    name: "Color Balance",
    category: "Color Correction",
    description: "Shadow, midtone, and highlight color balance.",
    execution: "fused-pixel",
    parameters: [
      number("shadows", "Shadow Balance", 0, -1, 1, 0.01),
      number("midtones", "Midtone Balance", 0, -1, 1, 0.01),
      number("highlights", "Highlight Balance", 0, -1, 1, 0.01),
      toggle("preserveLuminosity", "Preserve Luminosity"),
    ],
  },
  {
    type: "color-matrix",
    name: "Color Matrix",
    category: "Channel",
    description: "Fusible 4×5 color transform.",
    execution: "fused-pixel",
    parameters: [
      number("contrast", "Contrast", 1, 0, 3, 0.01),
      number("saturation", "Saturation", 1, 0, 3, 0.01),
      number("gain", "Gain", 1, 0, 8, 0.01),
    ],
  },
  {
    type: "channel-mixer",
    name: "Channel Mixer",
    category: "Channel",
    description: "Mix RGB channels in linear light.",
    execution: "fused-pixel",
    parameters: [
      number("red", "Red Gain", 1, -2, 2, 0.01),
      number("green", "Green Gain", 1, -2, 2, 0.01),
      number("blue", "Blue Gain", 1, -2, 2, 0.01),
      toggle("monochrome", "Monochrome", 0),
    ],
  },
  {
    type: "minimax",
    name: "Minimax",
    category: "Channel",
    description: "GPU morphological grow/shrink operation.",
    execution: "compute",
    parameters: [
      number("radius", "Radius", 2, 0, 127, 1, "px"),
      choice("operation", "Operation", ["Maximum", "Minimum"]),
      choice("channel", "Channel", ["Color", "Alpha"]),
    ],
  },
  {
    type: "displacement-map",
    name: "Displacement Map",
    category: "Distort",
    description: "Texture-driven UV displacement.",
    execution: "fused-pixel",
    parameters: [
      number("horizontal", "Horizontal", 25, -1000, 1000, 0.5, "px"),
      number("vertical", "Vertical", 25, -1000, 1000, 0.5, "px"),
      choice("channel", "Map Channel", ["Luminance", "Red", "Green", "Blue", "Alpha"]),
    ],
  },
  {
    type: "turbulent-displace",
    name: "Turbulent Displace",
    category: "Distort",
    description: "Procedural noise displacement.",
    execution: "compute",
    parameters: [
      number("amount", "Amount", 50, 0, 500, 1, "px"),
      number("size", "Size", 100, 2, 2000, 1, "px"),
      number("complexity", "Complexity", 2, 1, 10, 0.1),
      number("evolution", "Evolution", 0, -100, 100, 0.1),
    ],
  },
  {
    type: "wave-warp",
    name: "Wave Warp",
    category: "Distort",
    description: "Analytic sine, square, and triangle deformation.",
    execution: "fused-pixel",
    parameters: [
      choice("waveType", "Wave Type", ["Sine", "Square", "Triangle", "Sawtooth"]),
      number("height", "Wave Height", 24, 0, 1000, 1, "px"),
      number("width", "Wave Width", 320, 1, 4000, 1, "px"),
      angle("direction", "Direction", 90),
      number("speed", "Wave Speed", 1, -10, 10, 0.1),
    ],
  },
  {
    type: "twirl",
    name: "Twirl",
    category: "Distort",
    description: "Twist pixels around a center point.",
    execution: "fused-pixel",
    parameters: [
      angle("angle", "Twirl Angle", 60),
      number("radius", "Twirl Radius", 280, 0, 4000, 1, "px"),
    ],
  },
  {
    type: "bulge",
    name: "Bulge",
    category: "Distort",
    description: "Lens-like radial bulge or pinch.",
    execution: "fused-pixel",
    parameters: [
      number("radius", "Radius", 300, 0, 4000, 1, "px"),
      number("height", "Bulge Height", 0.5, -1, 4, 0.01),
      number("taper", "Taper Radius", 1, 0, 1, 0.01),
    ],
  },
  {
    type: "chromatic",
    name: "Chromatic Aberration",
    category: "Distort",
    description: "Lens RGB channel separation.",
    execution: "fused-pixel",
    parameters: [
      number("amount", "Amount", 6, 0, 100, 0.1, "px"),
      angle("angle", "Direction", 0),
      number("falloff", "Edge Falloff", 1, 0, 4, 0.01),
    ],
  },
  {
    type: "transform",
    name: "Transform",
    category: "Distort",
    description: "Effect-space transform with motion blur.",
    execution: "fused-pixel",
    parameters: [
      number("positionX", "Position X", 0, -8000, 8000, 0.5, "px"),
      number("positionY", "Position Y", 0, -8000, 8000, 0.5, "px"),
      number("scale", "Scale", 100, 0, 1000, 0.1, "%"),
      angle("rotation", "Rotation", 0),
      number("shutter", "Shutter Angle", 0, 0, 720, 1, "°"),
    ],
  },
  {
    type: "fractal-noise",
    name: "Fractal Noise",
    category: "Generate",
    description: "Compute-generated multi-octave noise.",
    execution: "compute",
    parameters: [
      choice("fractalType", "Fractal Type", ["Basic", "Turbulent", "Dynamic"]),
      number("contrast", "Contrast", 1.2, 0, 5, 0.01),
      number("brightness", "Brightness", 0, -1, 1, 0.01),
      number("scale", "Scale", 180, 1, 4000, 1, "px"),
      number("complexity", "Complexity", 4, 1, 12, 0.1),
      number("evolution", "Evolution", 0, -1000, 1000, 0.1),
    ],
  },
  {
    type: "four-color-gradient",
    name: "4-Color Gradient",
    category: "Generate",
    description: "Four-point linear-light gradient generator.",
    execution: "fused-pixel",
    parameters: [
      color("color1", "Color 1", 0x172968),
      color("color2", "Color 2", 0x723dd8),
      color("color3", "Color 3", 0x189bc0),
      color("color4", "Color 4", 0x0b1029),
      number("blend", "Blend", 0.5, 0, 1, 0.01),
    ],
  },
  {
    type: "checkerboard",
    name: "Checkerboard",
    category: "Generate",
    description: "Resolution-independent checkerboard.",
    execution: "fused-pixel",
    parameters: [
      number("size", "Size", 80, 1, 2000, 1, "px"),
      color("color1", "Color 1", 0x141824),
      color("color2", "Color 2", 0x334267),
      percent("opacity", "Opacity", 100),
    ],
  },
  {
    type: "grid",
    name: "Grid",
    category: "Generate",
    description: "GPU analytic grid generator.",
    execution: "fused-pixel",
    parameters: [
      number("width", "Width", 120, 2, 4000, 1, "px"),
      number("height", "Height", 120, 2, 4000, 1, "px"),
      number("border", "Border", 2, 0, 100, 0.5, "px"),
      color("color", "Color", 0x6f86b7),
    ],
  },
  {
    type: "glow",
    name: "Glow",
    category: "Stylize",
    description: "Thresholded HDR bloom with multi-resolution blur.",
    execution: "multi-pass",
    parameters: [
      number("threshold", "Glow Threshold", 0.65, 0, 4, 0.01),
      number("radius", "Glow Radius", 42, 0, 1000, 0.5, "px"),
      number("intensity", "Glow Intensity", 1.1, 0, 10, 0.05),
      choice("composite", "Composite", ["On Original", "Behind", "Glow Only"]),
    ],
  },
  {
    type: "bloom",
    name: "Filmic Bloom",
    category: "Stylize",
    description: "Looks-style soft highlight rolloff and bloom.",
    execution: "multi-pass",
    parameters: [
      number("threshold", "Threshold", 0.8, 0, 8, 0.01),
      number("radius", "Radius", 96, 0, 2000, 1, "px"),
      number("intensity", "Intensity", 0.8, 0, 10, 0.05),
      number("anamorphic", "Anamorphic", 0, -1, 1, 0.01),
    ],
  },
  {
    type: "find-edges",
    name: "Find Edges",
    category: "Stylize",
    description: "Sobel edge detection.",
    execution: "fused-pixel",
    parameters: [toggle("invert", "Invert", 0), percent("blend", "Blend With Original", 0)],
  },
  {
    type: "mosaic",
    name: "Mosaic",
    category: "Stylize",
    description: "GPU pixelation with sharp colors.",
    execution: "fused-pixel",
    parameters: [
      number("blocksX", "Horizontal Blocks", 64, 1, 2000, 1),
      number("blocksY", "Vertical Blocks", 36, 1, 2000, 1),
      toggle("sharp", "Sharp Colors"),
    ],
  },
  {
    type: "posterize",
    name: "Posterize",
    category: "Stylize",
    description: "Reduce color levels per channel.",
    execution: "fused-pixel",
    parameters: [number("levels", "Levels", 8, 2, 256, 1)],
  },
  {
    type: "emboss",
    name: "Emboss",
    category: "Stylize",
    description: "Directional relief lighting.",
    execution: "fused-pixel",
    parameters: [
      angle("direction", "Direction", 135),
      number("relief", "Relief", 2, 0, 20, 0.1),
      number("contrast", "Contrast", 1, 0, 10, 0.1),
      percent("blend", "Blend With Original", 0),
    ],
  },
  {
    type: "chroma-key",
    name: "Chroma Key",
    category: "Keying",
    description: "GPU chroma key with spill suppression.",
    execution: "fused-pixel",
    parameters: [
      color("keyColor", "Key Color", 0x00ff65),
      number("tolerance", "Tolerance", 0.18, 0, 1, 0.01),
      number("softness", "Softness", 0.08, 0, 1, 0.01),
      number("spill", "Spill Suppression", 0.6, 0, 1, 0.01),
    ],
  },
  {
    type: "luma-key",
    name: "Luma Key",
    category: "Keying",
    description: "Key pixels by luminance range.",
    execution: "fused-pixel",
    parameters: [
      choice("mode", "Key Type", ["Key Darker", "Key Brighter"]),
      number("threshold", "Threshold", 0.5, 0, 1, 0.01),
      number("softness", "Softness", 0.1, 0, 1, 0.01),
    ],
  },
  {
    type: "spill-suppressor",
    name: "Advanced Spill Suppressor",
    category: "Keying",
    description: "Remove green or blue screen contamination.",
    execution: "fused-pixel",
    parameters: [
      choice("color", "Key Color", ["Green", "Blue"]),
      number("amount", "Amount", 1, 0, 2, 0.01),
      number("range", "Range", 0.5, 0, 1, 0.01),
    ],
  },
  {
    type: "echo",
    name: "Echo",
    category: "Time",
    description: "Cache-backed temporal echo compositing.",
    execution: "temporal",
    parameters: [
      number("echoTime", "Echo Time", -0.033, -10, 10, 0.001, "s"),
      number("echoes", "Number of Echoes", 8, 1, 128, 1),
      number("decay", "Decay", 0.8, 0, 2, 0.01),
      choice("operator", "Echo Operator", ["Add", "Maximum", "Screen", "Composite"]),
    ],
  },
  {
    type: "posterize-time",
    name: "Posterize Time",
    category: "Time",
    description: "Quantize arbitrary-time evaluation to a target frame rate.",
    execution: "temporal",
    parameters: [number("frameRate", "Frame Rate", 12, 1, 240, 0.001, "fps")],
  },
  {
    type: "motion-trails",
    name: "Motion Trails",
    category: "Time",
    description: "Motion-vector-aware temporal trails.",
    execution: "temporal",
    parameters: [
      number("samples", "Samples", 12, 2, 64, 1),
      number("duration", "Duration", 0.35, 0, 5, 0.01, "s"),
      number("decay", "Decay", 0.82, 0, 1, 0.01),
    ],
  },
  {
    type: "linear-wipe",
    name: "Linear Wipe",
    category: "Transition",
    description: "Angle-addressable feathered wipe.",
    execution: "fused-pixel",
    parameters: [
      percent("completion", "Transition Completion", 50),
      angle("angle", "Wipe Angle", 0),
      number("feather", "Feather", 0, 0, 2000, 1, "px"),
    ],
  },
  {
    type: "radial-wipe",
    name: "Radial Wipe",
    category: "Transition",
    description: "Clockwise or counter-clockwise radial reveal.",
    execution: "fused-pixel",
    parameters: [
      percent("completion", "Transition Completion", 50),
      angle("startAngle", "Start Angle", 0),
      number("feather", "Feather", 0, 0, 180, 0.1, "°"),
    ],
  },
  {
    type: "particle-world",
    name: "GPU Particle World",
    category: "Simulation",
    description: "Compute-simulated deterministic particle system.",
    execution: "compute",
    parameters: [
      number("birthRate", "Birth Rate", 2, 0, 100, 0.1),
      number("longevity", "Longevity", 3, 0.01, 120, 0.01, "s"),
      number("velocity", "Velocity", 1, 0, 100, 0.01),
      number("gravity", "Gravity", 0.5, -10, 10, 0.01),
      number("seed", "Random Seed", 1, 0, 65535, 1),
    ],
  },
  {
    type: "looks-color-lab",
    name: "Looks Color Lab",
    category: "Looks",
    description: "Filmic all-in-one grading with GPU-fused controls.",
    execution: "fused-pixel",
    parameters: [
      number("temperature", "Temperature", 0, -1, 1, 0.01),
      number("tint", "Tint", 0, -1, 1, 0.01),
      number("exposure", "Exposure", 0, -8, 8, 0.05, "EV"),
      number("contrast", "Filmic Contrast", 1.08, 0, 3, 0.01),
      number("pivot", "Contrast Pivot", 0.42, 0, 1, 0.01),
      number("saturation", "Saturation", 1, 0, 3, 0.01),
      number("vibrance", "Vibrance", 0.15, -1, 1, 0.01),
      number("lift", "Lift", 0, -1, 1, 0.01),
      number("gamma", "Gamma", 1, 0.1, 4, 0.01),
      number("gain", "Gain", 1, 0, 8, 0.01),
      number("fade", "Film Fade", 0, 0, 1, 0.01),
      number("vignette", "Vignette", 0.22, 0, 2, 0.01),
      number("grain", "Film Grain", 0.04, 0, 1, 0.005),
      number("bloom", "Bloom", 0.35, 0, 4, 0.01),
    ],
  },
  {
    type: "film-emulation",
    name: "Film Emulation",
    category: "Looks",
    description: "Filmic shoulder, toe, grain, halation, and gate weave.",
    execution: "multi-pass",
    parameters: [
      choice("stock", "Film Stock", ["Neutral 250D", "Warm 500T", "Reversal", "Bleach Bypass"]),
      number("strength", "Strength", 1, 0, 2, 0.01),
      number("grain", "Grain", 0.08, 0, 1, 0.005),
      number("halation", "Halation", 0.18, 0, 2, 0.01),
      number("weave", "Gate Weave", 0, 0, 10, 0.1, "px"),
    ],
  },
  {
    type: "split-tone",
    name: "Split Tone",
    category: "Looks",
    description: "Independent shadow and highlight tinting.",
    execution: "fused-pixel",
    parameters: [
      angle("shadowHue", "Shadow Hue", 220),
      number("shadowAmount", "Shadow Amount", 0.12, 0, 1, 0.01),
      angle("highlightHue", "Highlight Hue", 38),
      number("highlightAmount", "Highlight Amount", 0.1, 0, 1, 0.01),
      number("balance", "Balance", 0, -1, 1, 0.01),
    ],
  },
  {
    type: "lut",
    name: "3D LUT",
    category: "Looks",
    description: "Trilinear GPU 3D LUT application.",
    execution: "fused-pixel",
    parameters: [
      percent("intensity", "Intensity", 100),
      choice("interpolation", "Interpolation", ["Trilinear", "Tetrahedral"]),
    ],
  },
];

export const EFFECT_BY_TYPE = new Map(EFFECT_REGISTRY.map((effect) => [effect.type, effect]));

export function createEffect(type: string): Effect {
  const definition = EFFECT_BY_TYPE.get(type);
  if (!definition) throw new Error(`Unknown effect type: ${type}`);
  return {
    id: createId(),
    type,
    name: definition.name,
    enabled: true,
    parameters: Object.fromEntries(
      definition.parameters.map((parameter) => [parameter.key, parameter.defaultValue]),
    ),
  };
}

export function effectCategories(): string[] {
  return [...new Set(EFFECT_REGISTRY.map((effect) => effect.category))];
}
