import { angle, color, number, percent } from "./parameter-builders";
import type { EffectDefinition } from "./types";

export const SIMULATION_EFFECTS: EffectDefinition[] = [
  {
    type: "bubbles",
    name: "CC Bubbles",
    category: "Simulation",
    description: "Generate rising refractive bubbles with deterministic wobble and density.",
    execution: "compute",
    parameters: [
      number("amount", "Bubble Amount", 55, 1, 500, 1),
      number("size", "Bubble Size", 14, 1, 256, 0.5, "px"),
      number("speed", "Rise Speed", 85, -1000, 1000, 1, "px/s"),
      number("wobble", "Wobble", 18, 0, 500, 1, "px"),
      number("refraction", "Refraction", 0.65, 0, 4, 0.01),
      color("color", "Bubble Color", 0xbcecff),
      number("seed", "Random Seed", 1, 0, 65535, 1),
    ],
  },
  {
    type: "drizzle",
    name: "CC Drizzle",
    category: "Simulation",
    description: "Simulate randomized water impacts and expanding surface ripples.",
    execution: "compute",
    parameters: [
      number("rate", "Drizzle Rate", 3, 0.1, 30, 0.1),
      number("radius", "Ripple Radius", 42, 1, 1000, 1, "px"),
      number("width", "Ripple Width", 3, 0.5, 64, 0.5, "px"),
      number("speed", "Expansion Speed", 120, 1, 2000, 1, "px/s"),
      number("disturbance", "Surface Disturbance", 0.7, 0, 4, 0.01),
      color("color", "Ripple Color", 0x7fc8ff),
      number("seed", "Random Seed", 1, 0, 65535, 1),
    ],
  },
  {
    type: "hair",
    name: "CC Hair",
    category: "Simulation",
    description: "Grow animated procedural strands with directional wave motion.",
    execution: "compute",
    parameters: [
      number("density", "Density", 32, 2, 256, 1),
      number("length", "Length", 48, 1, 1000, 1, "px"),
      number("thickness", "Thickness", 1.5, 0.25, 32, 0.25, "px"),
      angle("direction", "Direction", -90),
      number("wave", "Wave", 18, 0, 500, 1, "px"),
      number("speed", "Wave Speed", 2, -20, 20, 0.1),
      color("color", "Hair Color", 0xd5e7ff),
      percent("opacity", "Opacity", 85),
    ],
  },
  {
    type: "mr-mercury",
    name: "CC Mr. Mercury",
    category: "Simulation",
    description: "Generate animated metallic metaballs emitted from a movable producer.",
    execution: "compute",
    parameters: [
      percent("producerX", "Producer X", 50),
      percent("producerY", "Producer Y", 45),
      number("blobSize", "Blob Size", 54, 2, 1000, 1, "px"),
      number("velocity", "Velocity", 120, 0, 2000, 1, "px/s"),
      number("gravity", "Gravity", 80, -2000, 2000, 1, "px/s²"),
      number("viscosity", "Viscosity", 1.3, 0.1, 8, 0.05),
      color("color", "Mercury Color", 0xaed8ff),
      number("seed", "Random Seed", 1, 0, 65535, 1),
    ],
  },
  {
    type: "particle-systems-ii",
    name: "CC Particle Systems II",
    category: "Simulation",
    description: "Render deterministic GPU particles with directional emission and gravity.",
    execution: "compute",
    parameters: [
      percent("producerX", "Producer X", 50),
      percent("producerY", "Producer Y", 50),
      number("birthRate", "Birth Rate", 4, 0.1, 50, 0.1),
      number("longevity", "Longevity", 2.5, 0.1, 30, 0.1, "s"),
      number("velocity", "Velocity", 180, 0, 2000, 1, "px/s"),
      angle("direction", "Direction", -90),
      angle("spread", "Spread", 45),
      number("gravity", "Gravity", 120, -2000, 2000, 1, "px/s²"),
      number("size", "Particle Size", 5, 0.5, 128, 0.5, "px"),
      color("color", "Particle Color", 0x80c8ff),
      number("seed", "Random Seed", 1, 0, 65535, 1),
    ],
  },
  {
    type: "pixel-polly",
    name: "CC Pixel Polly",
    category: "Simulation",
    description: "Fracture the source into deterministic tiles and launch them with gravity.",
    execution: "compute",
    parameters: [
      percent("completion", "Explosion", 45),
      number("tileSize", "Tile Size", 42, 4, 512, 1, "px"),
      number("scatter", "Scatter", 360, 0, 4000, 1, "px"),
      number("gravity", "Gravity", 280, -4000, 4000, 1, "px"),
      number("randomness", "Randomness", 1, 0, 4, 0.01),
      number("seed", "Random Seed", 1, 0, 65535, 1),
      percent("fade", "Fade", 20),
    ],
  },
  {
    type: "scatterize",
    name: "CC Scatterize",
    category: "Simulation",
    description: "Scatter animated blocks with rotation-biased deterministic motion.",
    execution: "compute",
    parameters: [
      number("scatterX", "Scatter X", 80, -2000, 2000, 1, "px"),
      number("scatterY", "Scatter Y", 80, -2000, 2000, 1, "px"),
      number("grain", "Grain", 48, 2, 1000, 1, "px"),
      angle("twist", "Twist", 12),
      number("evolution", "Evolution", 0, -1000, 1000, 0.1),
      percent("blend", "Scatter Amount", 100),
      number("seed", "Random Seed", 1, 0, 65535, 1),
    ],
  },
  {
    type: "wave-world",
    name: "Wave World",
    category: "Simulation",
    description: "Generate a damped animated height field with reflective wave shading.",
    execution: "compute",
    parameters: [
      percent("centerX", "Producer X", 50),
      percent("centerY", "Producer Y", 50),
      number("frequency", "Wave Frequency", 7, 0.1, 64, 0.1),
      number("speed", "Wave Speed", 2, -20, 20, 0.1),
      number("damping", "Damping", 1.8, 0.01, 12, 0.01),
      number("height", "Wave Height", 0.8, 0, 8, 0.01),
      color("color", "Wave Color", 0x4c9fe8),
      percent("blend", "Blend With Original", 75),
    ],
  },
];
