import { angle, choice, color, number, percent, toggle } from "./parameter-builders";
import type { EffectDefinition } from "./types";

export const ADVANCED_STYLIZE_EFFECTS: EffectDefinition[] = [
  {
    type: "color-halftone",
    name: "Color Halftone",
    category: "Stylize",
    description: "Render angle-separated CMYK-style halftone dots at a configurable radius.",
    execution: "fused-pixel",
    parameters: [
      number("radius", "Maximum Radius", 8, 1, 128, 0.5, "px"),
      angle("redAngle", "Red Screen Angle", 15),
      angle("greenAngle", "Green Screen Angle", 45),
      angle("blueAngle", "Blue Screen Angle", 75),
      toggle("monochrome", "Monochrome", 0),
      percent("blend", "Blend With Original", 100),
    ],
  },
  {
    type: "glowing-edges",
    name: "Glowing Edges",
    category: "Stylize",
    description: "Extract and colorize high-contrast edges with HDR glow intensity.",
    execution: "multi-pass",
    parameters: [
      number("width", "Edge Width", 1.5, 0.25, 64, 0.25, "px"),
      number("threshold", "Edge Threshold", 0.08, 0, 1, 0.005),
      number("intensity", "Glow Intensity", 2, 0, 20, 0.05),
      color("color", "Glow Color", 0x5bc8ff),
      toggle("invert", "Invert Background", 0),
      percent("blend", "Blend With Original", 100),
    ],
  },
  {
    type: "texturize",
    name: "Texturize",
    category: "Stylize",
    description: "Emboss deterministic procedural texture into the source surface.",
    execution: "fused-pixel",
    parameters: [
      number("scale", "Texture Scale", 64, 2, 2000, 1, "px"),
      number("relief", "Relief", 1.2, 0, 8, 0.05),
      angle("lightDirection", "Light Direction", 135),
      number("contrast", "Texture Contrast", 1, 0, 8, 0.05),
      number("evolution", "Evolution", 0, -1000, 1000, 0.1),
      percent("blend", "Blend With Original", 100),
    ],
  },
  {
    type: "tiles",
    name: "Tiles",
    category: "Stylize",
    description: "Repeat the source into offset tiles with optional mirroring and grout.",
    execution: "fused-pixel",
    parameters: [
      number("columns", "Columns", 4, 1, 64, 1),
      number("rows", "Rows", 4, 1, 64, 1),
      percent("offsetX", "Offset X", 0),
      percent("offsetY", "Offset Y", 0),
      toggle("mirror", "Mirror Tiles", 1),
      percent("grout", "Grout Width", 2),
      color("groutColor", "Grout Color", 0x111521),
    ],
  },
  {
    type: "cc-threshold",
    name: "CC Threshold",
    category: "Stylize",
    description: "Threshold luminance, RGB maximum, or alpha with a soft edge.",
    execution: "fused-pixel",
    parameters: [
      number("level", "Threshold", 0.5, 0, 1, 0.001),
      number("softness", "Softness", 0.02, 0, 0.5, 0.001),
      choice("channel", "Channel", ["Luminance", "RGB Maximum", "Alpha"]),
      toggle("invert", "Invert", 0),
      percent("blend", "Blend With Original", 100),
    ],
  },
  {
    type: "cc-toner",
    name: "CC Toner",
    category: "Color Correction",
    description: "Map shadows, midtones, and highlights through a three-color toner palette.",
    execution: "fused-pixel",
    parameters: [
      color("shadows", "Shadows", 0x102048),
      color("midtones", "Midtones", 0x8b5fc7),
      color("highlights", "Highlights", 0xffd6a0),
      number("balance", "Balance", 0, -1, 1, 0.01),
      percent("blend", "Blend With Original", 100),
    ],
  },
  {
    type: "cc-plastic",
    name: "CC Plastic",
    category: "Stylize",
    description: "Shade source luminance as a smooth plastic surface with specular light.",
    execution: "multi-pass",
    parameters: [
      number("softness", "Surface Softness", 3, 0.5, 128, 0.5, "px"),
      number("height", "Height", 2, 0, 20, 0.05),
      angle("lightDirection", "Light Direction", 315),
      number("specular", "Specular", 1.5, 0, 12, 0.05),
      color("color", "Plastic Color", 0x70a8ff),
      percent("blend", "Blend With Original", 100),
    ],
  },
  {
    type: "cc-blobbylize",
    name: "CC Blobbylize",
    category: "Stylize",
    description: "Convert source luminance into soft shaded organic blobs.",
    execution: "multi-pass",
    parameters: [
      number("softness", "Blob Softness", 18, 0.5, 500, 0.5, "px"),
      number("threshold", "Blob Threshold", 0.48, 0, 1, 0.005),
      number("cutAway", "Cut Away", 0.08, 0, 1, 0.005),
      angle("lightDirection", "Light Direction", 315),
      number("lightIntensity", "Light Intensity", 1.4, 0, 12, 0.05),
      color("color", "Blob Color", 0x6cb8ff),
      percent("blend", "Blend With Original", 100),
    ],
  },
];
