import { angle, color, number, percent, toggle } from "./parameter-builders";
import type { EffectDefinition } from "./types";

export const ADVANCED_TRANSITIONS: EffectDefinition[] = [
  {
    type: "clock-wipe",
    name: "Clock Wipe",
    category: "Transition",
    description: "Reveal the layer with a feathered clockwise or counter-clockwise sweep.",
    execution: "fused-pixel",
    parameters: [
      percent("completion", "Transition Completion", 50),
      angle("startAngle", "Start Angle", -90),
      number("feather", "Feather", 3, 0, 180, 0.1, "°"),
      toggle("counterClockwise", "Counter Clockwise", 0),
    ],
  },
  {
    type: "grid-wipe",
    name: "CC Grid Wipe",
    category: "Transition",
    description: "Reveal randomized grid cells with a controllable border and soft timing edge.",
    execution: "fused-pixel",
    parameters: [
      percent("completion", "Completion", 50),
      number("columns", "Columns", 12, 1, 128, 1),
      number("rows", "Rows", 7, 1, 128, 1),
      percent("border", "Border", 8),
      percent("softness", "Transition Softness", 12),
      number("seed", "Random Seed", 1, 0, 65535, 1),
    ],
  },
  {
    type: "jaws",
    name: "CC Jaws",
    category: "Transition",
    description: "Close interlocking procedural teeth across the layer alpha.",
    execution: "fused-pixel",
    parameters: [
      percent("completion", "Completion", 50),
      angle("direction", "Direction", 0),
      number("teeth", "Number of Teeth", 12, 2, 128, 1),
      percent("toothDepth", "Tooth Depth", 35),
      number("feather", "Feather", 3, 0, 500, 0.5, "px"),
      toggle("invert", "Invert", 0),
    ],
  },
  {
    type: "light-wipe",
    name: "CC Light Wipe",
    category: "Transition",
    description: "Drive a directional alpha wipe with an HDR luminous edge.",
    execution: "fused-pixel",
    parameters: [
      percent("completion", "Completion", 50),
      angle("direction", "Direction", 0),
      number("width", "Light Width", 80, 1, 2000, 1, "px"),
      number("intensity", "Light Intensity", 2, 0, 20, 0.05),
      color("color", "Light Color", 0xa8dcff),
      number("feather", "Edge Feather", 12, 0, 500, 0.5, "px"),
    ],
  },
  {
    type: "line-sweep",
    name: "CC Line Sweep",
    category: "Transition",
    description: "Sweep a feathered line across the layer with an optional inverted reveal.",
    execution: "fused-pixel",
    parameters: [
      percent("completion", "Completion", 50),
      angle("direction", "Direction", 0),
      number("width", "Line Width", 12, 0.5, 1000, 0.5, "px"),
      number("feather", "Feather", 8, 0, 500, 0.5, "px"),
      toggle("invert", "Invert", 0),
    ],
  },
  {
    type: "scale-wipe",
    name: "CC Scale Wipe",
    category: "Transition",
    description: "Reveal and scale the source around a movable center point.",
    execution: "fused-pixel",
    parameters: [
      percent("completion", "Completion", 50),
      percent("centerX", "Center X", 50),
      percent("centerY", "Center Y", 50),
      angle("rotation", "Rotation", 0),
      number("feather", "Feather", 12, 0, 500, 0.5, "px"),
    ],
  },
  {
    type: "twister",
    name: "CC Twister",
    category: "Transition",
    description: "Twist the source into or out of view around a configurable radial region.",
    execution: "fused-pixel",
    parameters: [
      percent("completion", "Completion", 50),
      percent("centerX", "Center X", 50),
      percent("centerY", "Center Y", 50),
      number("twists", "Twists", 1.5, -8, 8, 0.05),
      number("radius", "Radius", 640, 1, 8000, 1, "px"),
      number("feather", "Feather", 32, 0, 1000, 1, "px"),
    ],
  },
  {
    type: "card-wipe",
    name: "Card Wipe",
    category: "Transition",
    description: "Flip a randomized field of cards to reveal their shaded back faces.",
    execution: "fused-pixel",
    parameters: [
      percent("completion", "Transition Completion", 50),
      number("columns", "Columns", 12, 1, 128, 1),
      number("rows", "Rows", 7, 1, 128, 1),
      percent("randomness", "Random Order", 75),
      number("seed", "Random Seed", 1, 0, 65535, 1),
      color("backColor", "Back Color", 0x29324d),
      percent("backOpacity", "Back Opacity", 90),
    ],
  },
];
